/********************************************************************************
** Form generated from reading ui file 'bravenewmodder.ui'
**
** Created: Tue May 26 03:08:32 2009
**      by: Qt User Interface Compiler version 4.5.0
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_BRAVENEWMODDER_H
#define UI_BRAVENEWMODDER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QScrollArea>
#include <QtGui/QTabWidget>
#include <QtGui/QTreeView>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_BravenewmodderClass
{
public:
    QAction *actionNew_Mod;
    QAction *actionLoad_Mod;
    QAction *actionSave_Mod;
    QAction *actionExport_Mod;
    QAction *actionExit;
    QAction *actionForce_Check;
    QAction *actionSuggested;
    QAction *actionOff;
    QAction *actionUnlimited_Play;
    QAction *actionHelp;
    QAction *actionAbout;
    QAction *actionAdd_New_Syntax;
    QAction *actionManage_My_Mod;
    QAction *actionEvent_Renumeration;
    QAction *actionLocalisation_Check;
    QAction *actionCreate_QuickScript;
    QAction *actionGenerate;
    QAction *actionGenerate_List;
    QAction *actionImport_Content;
    QAction *actionUndo;
    QAction *actionEditor_Settings;
    QAction *actionEnglish;
    QAction *actionEnable;
    QAction *actionDisable;
    QAction *actionMod_Settings;
    QWidget *centralWidget;
    QTabWidget *tbxMain;
    QWidget *tabCommon;
    QTreeView *trvEvents_4;
    QScrollArea *scrollArea_4;
    QWidget *scrollAreaWidgetContents_4;
    QGroupBox *groupBox_4;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QWidget *tab;
    QTreeView *trvEvents_3;
    QScrollArea *scrollArea_3;
    QWidget *scrollAreaWidgetContents_3;
    QGroupBox *groupBox_2;
    QPushButton *pushButton_13;
    QPushButton *pushButton_12;
    QPushButton *pushButton_7;
    QPushButton *pushButton_9;
    QPushButton *pushButton_8;
    QPushButton *pushButton_11;
    QPushButton *pushButton_10;
    QWidget *TabEvents;
    QTreeView *trvEvents;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QWidget *tabHistory;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QWidget *tab_3;
    QWidget *tab_4;
    QWidget *tab_5;
    QWidget *tab_6;
    QGroupBox *groupBox_6;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QScrollArea *scrollArea_5;
    QWidget *scrollAreaWidgetContents_5;
    QTreeView *trvEvents_5;
    QWidget *tabInterface;
    QWidget *tabLocalisation;
    QTreeView *treeView_2;
    QWidget *tabMap;
    QTabWidget *tabWidget_2;
    QWidget *tab_7;
    QTreeView *treeView;
    QWidget *tab_8;
    QWidget *tab_9;
    QWidget *tab_10;
    QWidget *tab_11;
    QWidget *tabMissions;
    QTreeView *trvEvents_2;
    QGroupBox *groupBox_5;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QWidget *tab_12;
    QWidget *tabReference;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuSettings;
    QMenu *menuSyntax_Check;
    QMenu *menuEditor_Language;
    QMenu *menuBNM_Event_Convention;
    QMenu *menuHelp;
    QMenu *menuTools;

    void setupUi(QMainWindow *BravenewmodderClass)
    {
        if (BravenewmodderClass->objectName().isEmpty())
            BravenewmodderClass->setObjectName(QString::fromUtf8("BravenewmodderClass"));
        BravenewmodderClass->resize(1024, 768);
        BravenewmodderClass->setMinimumSize(QSize(1024, 768));
        BravenewmodderClass->setMaximumSize(QSize(1024, 768));
        actionNew_Mod = new QAction(BravenewmodderClass);
        actionNew_Mod->setObjectName(QString::fromUtf8("actionNew_Mod"));
        actionLoad_Mod = new QAction(BravenewmodderClass);
        actionLoad_Mod->setObjectName(QString::fromUtf8("actionLoad_Mod"));
        actionSave_Mod = new QAction(BravenewmodderClass);
        actionSave_Mod->setObjectName(QString::fromUtf8("actionSave_Mod"));
        actionExport_Mod = new QAction(BravenewmodderClass);
        actionExport_Mod->setObjectName(QString::fromUtf8("actionExport_Mod"));
        actionExit = new QAction(BravenewmodderClass);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionForce_Check = new QAction(BravenewmodderClass);
        actionForce_Check->setObjectName(QString::fromUtf8("actionForce_Check"));
        actionForce_Check->setCheckable(true);
        actionForce_Check->setAutoRepeat(false);
        actionSuggested = new QAction(BravenewmodderClass);
        actionSuggested->setObjectName(QString::fromUtf8("actionSuggested"));
        actionSuggested->setCheckable(true);
        actionSuggested->setAutoRepeat(false);
        actionOff = new QAction(BravenewmodderClass);
        actionOff->setObjectName(QString::fromUtf8("actionOff"));
        actionOff->setCheckable(true);
        actionOff->setAutoRepeat(false);
        actionUnlimited_Play = new QAction(BravenewmodderClass);
        actionUnlimited_Play->setObjectName(QString::fromUtf8("actionUnlimited_Play"));
        actionHelp = new QAction(BravenewmodderClass);
        actionHelp->setObjectName(QString::fromUtf8("actionHelp"));
        actionAbout = new QAction(BravenewmodderClass);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionAdd_New_Syntax = new QAction(BravenewmodderClass);
        actionAdd_New_Syntax->setObjectName(QString::fromUtf8("actionAdd_New_Syntax"));
        actionManage_My_Mod = new QAction(BravenewmodderClass);
        actionManage_My_Mod->setObjectName(QString::fromUtf8("actionManage_My_Mod"));
        actionEvent_Renumeration = new QAction(BravenewmodderClass);
        actionEvent_Renumeration->setObjectName(QString::fromUtf8("actionEvent_Renumeration"));
        actionLocalisation_Check = new QAction(BravenewmodderClass);
        actionLocalisation_Check->setObjectName(QString::fromUtf8("actionLocalisation_Check"));
        actionCreate_QuickScript = new QAction(BravenewmodderClass);
        actionCreate_QuickScript->setObjectName(QString::fromUtf8("actionCreate_QuickScript"));
        actionGenerate = new QAction(BravenewmodderClass);
        actionGenerate->setObjectName(QString::fromUtf8("actionGenerate"));
        actionGenerate_List = new QAction(BravenewmodderClass);
        actionGenerate_List->setObjectName(QString::fromUtf8("actionGenerate_List"));
        actionImport_Content = new QAction(BravenewmodderClass);
        actionImport_Content->setObjectName(QString::fromUtf8("actionImport_Content"));
        actionUndo = new QAction(BravenewmodderClass);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        actionEditor_Settings = new QAction(BravenewmodderClass);
        actionEditor_Settings->setObjectName(QString::fromUtf8("actionEditor_Settings"));
        actionEnglish = new QAction(BravenewmodderClass);
        actionEnglish->setObjectName(QString::fromUtf8("actionEnglish"));
        actionEnable = new QAction(BravenewmodderClass);
        actionEnable->setObjectName(QString::fromUtf8("actionEnable"));
        actionDisable = new QAction(BravenewmodderClass);
        actionDisable->setObjectName(QString::fromUtf8("actionDisable"));
        actionMod_Settings = new QAction(BravenewmodderClass);
        actionMod_Settings->setObjectName(QString::fromUtf8("actionMod_Settings"));
        centralWidget = new QWidget(BravenewmodderClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tbxMain = new QTabWidget(centralWidget);
        tbxMain->setObjectName(QString::fromUtf8("tbxMain"));
        tbxMain->setGeometry(QRect(-10, 0, 1041, 761));
        tbxMain->setElideMode(Qt::ElideLeft);
        tbxMain->setUsesScrollButtons(false);
        tabCommon = new QWidget();
        tabCommon->setObjectName(QString::fromUtf8("tabCommon"));
        trvEvents_4 = new QTreeView(tabCommon);
        trvEvents_4->setObjectName(QString::fromUtf8("trvEvents_4"));
        trvEvents_4->setGeometry(QRect(10, 0, 171, 726));
        scrollArea_4 = new QScrollArea(tabCommon);
        scrollArea_4->setObjectName(QString::fromUtf8("scrollArea_4"));
        scrollArea_4->setGeometry(QRect(180, 40, 561, 688));
        scrollArea_4->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_4->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        scrollArea_4->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_4"));
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 541, 684));
        scrollArea_4->setWidget(scrollAreaWidgetContents_4);
        groupBox_4 = new QGroupBox(tabCommon);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(180, 0, 561, 41));
        groupBox_4->setAlignment(Qt::AlignCenter);
        pushButton_21 = new QPushButton(groupBox_4);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(150, 14, 75, 25));
        pushButton_22 = new QPushButton(groupBox_4);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(0, 14, 75, 25));
        pushButton_23 = new QPushButton(groupBox_4);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(75, 14, 75, 25));
        pushButton_24 = new QPushButton(groupBox_4);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(225, 14, 75, 25));
        pushButton_25 = new QPushButton(groupBox_4);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(375, 14, 75, 25));
        pushButton_26 = new QPushButton(groupBox_4);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(300, 14, 75, 25));
        pushButton_27 = new QPushButton(groupBox_4);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(450, 14, 75, 25));
        tbxMain->addTab(tabCommon, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        trvEvents_3 = new QTreeView(tab);
        trvEvents_3->setObjectName(QString::fromUtf8("trvEvents_3"));
        trvEvents_3->setGeometry(QRect(10, 0, 171, 726));
        scrollArea_3 = new QScrollArea(tab);
        scrollArea_3->setObjectName(QString::fromUtf8("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(180, 40, 561, 688));
        scrollArea_3->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_3->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        scrollArea_3->setWidgetResizable(true);
        scrollAreaWidgetContents_3 = new QWidget();
        scrollAreaWidgetContents_3->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_3"));
        scrollAreaWidgetContents_3->setGeometry(QRect(0, 0, 541, 684));
        scrollArea_3->setWidget(scrollAreaWidgetContents_3);
        groupBox_2 = new QGroupBox(tab);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(180, 0, 561, 41));
        groupBox_2->setAlignment(Qt::AlignCenter);
        pushButton_13 = new QPushButton(groupBox_2);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(150, 14, 75, 25));
        pushButton_12 = new QPushButton(groupBox_2);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(0, 14, 75, 25));
        pushButton_7 = new QPushButton(groupBox_2);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(75, 14, 75, 25));
        pushButton_9 = new QPushButton(groupBox_2);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(225, 14, 75, 25));
        pushButton_8 = new QPushButton(groupBox_2);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(375, 14, 75, 25));
        pushButton_11 = new QPushButton(groupBox_2);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(300, 14, 75, 25));
        pushButton_10 = new QPushButton(groupBox_2);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(450, 14, 75, 25));
        tbxMain->addTab(tab, QString());
        TabEvents = new QWidget();
        TabEvents->setObjectName(QString::fromUtf8("TabEvents"));
        trvEvents = new QTreeView(TabEvents);
        trvEvents->setObjectName(QString::fromUtf8("trvEvents"));
        trvEvents->setGeometry(QRect(10, 0, 171, 726));
        scrollArea = new QScrollArea(TabEvents);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setGeometry(QRect(180, 40, 561, 688));
        scrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 541, 684));
        scrollArea->setWidget(scrollAreaWidgetContents);
        groupBox_3 = new QGroupBox(TabEvents);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(180, 0, 561, 41));
        groupBox_3->setAlignment(Qt::AlignCenter);
        pushButton_14 = new QPushButton(groupBox_3);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(150, 14, 75, 25));
        pushButton_15 = new QPushButton(groupBox_3);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(0, 14, 75, 25));
        pushButton_16 = new QPushButton(groupBox_3);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(75, 14, 75, 25));
        pushButton_17 = new QPushButton(groupBox_3);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(225, 14, 75, 25));
        pushButton_18 = new QPushButton(groupBox_3);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(375, 14, 75, 25));
        pushButton_19 = new QPushButton(groupBox_3);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(300, 14, 75, 25));
        pushButton_20 = new QPushButton(groupBox_3);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(450, 14, 75, 25));
        tbxMain->addTab(TabEvents, QString());
        tabHistory = new QWidget();
        tabHistory->setObjectName(QString::fromUtf8("tabHistory"));
        tabWidget = new QTabWidget(tabHistory);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(8, 0, 1024, 728));
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        groupBox_6 = new QGroupBox(tab_6);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(170, 0, 561, 41));
        groupBox_6->setAlignment(Qt::AlignCenter);
        pushButton_35 = new QPushButton(groupBox_6);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(150, 14, 75, 25));
        pushButton_36 = new QPushButton(groupBox_6);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(0, 14, 75, 25));
        pushButton_37 = new QPushButton(groupBox_6);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(75, 14, 75, 25));
        pushButton_38 = new QPushButton(groupBox_6);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(225, 14, 75, 25));
        pushButton_39 = new QPushButton(groupBox_6);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(375, 14, 75, 25));
        pushButton_40 = new QPushButton(groupBox_6);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(300, 14, 75, 25));
        pushButton_41 = new QPushButton(groupBox_6);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(450, 14, 75, 25));
        scrollArea_5 = new QScrollArea(tab_6);
        scrollArea_5->setObjectName(QString::fromUtf8("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(170, 40, 561, 664));
        scrollArea_5->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_5->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        scrollArea_5->setWidgetResizable(true);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_5"));
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 541, 660));
        scrollArea_5->setWidget(scrollAreaWidgetContents_5);
        trvEvents_5 = new QTreeView(tab_6);
        trvEvents_5->setObjectName(QString::fromUtf8("trvEvents_5"));
        trvEvents_5->setGeometry(QRect(0, 0, 171, 704));
        tabWidget->addTab(tab_6, QString());
        tbxMain->addTab(tabHistory, QString());
        tabInterface = new QWidget();
        tabInterface->setObjectName(QString::fromUtf8("tabInterface"));
        tbxMain->addTab(tabInterface, QString());
        tabLocalisation = new QWidget();
        tabLocalisation->setObjectName(QString::fromUtf8("tabLocalisation"));
        treeView_2 = new QTreeView(tabLocalisation);
        treeView_2->setObjectName(QString::fromUtf8("treeView_2"));
        treeView_2->setGeometry(QRect(8, 0, 201, 727));
        tbxMain->addTab(tabLocalisation, QString());
        tabMap = new QWidget();
        tabMap->setObjectName(QString::fromUtf8("tabMap"));
        tabWidget_2 = new QTabWidget(tabMap);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(8, 0, 1024, 727));
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        treeView = new QTreeView(tab_7);
        treeView->setObjectName(QString::fromUtf8("treeView"));
        treeView->setGeometry(QRect(0, 0, 131, 701));
        tabWidget_2->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        tabWidget_2->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        tabWidget_2->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        tabWidget_2->addTab(tab_10, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QString::fromUtf8("tab_11"));
        tabWidget_2->addTab(tab_11, QString());
        tbxMain->addTab(tabMap, QString());
        tabMissions = new QWidget();
        tabMissions->setObjectName(QString::fromUtf8("tabMissions"));
        trvEvents_2 = new QTreeView(tabMissions);
        trvEvents_2->setObjectName(QString::fromUtf8("trvEvents_2"));
        trvEvents_2->setGeometry(QRect(10, 0, 171, 726));
        groupBox_5 = new QGroupBox(tabMissions);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(180, 0, 561, 41));
        groupBox_5->setAlignment(Qt::AlignCenter);
        pushButton_28 = new QPushButton(groupBox_5);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(150, 14, 75, 25));
        pushButton_29 = new QPushButton(groupBox_5);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(0, 14, 75, 25));
        pushButton_30 = new QPushButton(groupBox_5);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(75, 14, 75, 25));
        pushButton_31 = new QPushButton(groupBox_5);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(225, 14, 75, 25));
        pushButton_32 = new QPushButton(groupBox_5);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(375, 14, 75, 25));
        pushButton_33 = new QPushButton(groupBox_5);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(300, 14, 75, 25));
        pushButton_34 = new QPushButton(groupBox_5);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(450, 14, 75, 25));
        scrollArea_2 = new QScrollArea(tabMissions);
        scrollArea_2->setObjectName(QString::fromUtf8("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(180, 40, 561, 688));
        scrollArea_2->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        scrollArea_2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 541, 684));
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        tbxMain->addTab(tabMissions, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QString::fromUtf8("tab_12"));
        tbxMain->addTab(tab_12, QString());
        tabReference = new QWidget();
        tabReference->setObjectName(QString::fromUtf8("tabReference"));
        tbxMain->addTab(tabReference, QString());
        BravenewmodderClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(BravenewmodderClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1024, 19));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuSettings = new QMenu(menuBar);
        menuSettings->setObjectName(QString::fromUtf8("menuSettings"));
        menuSyntax_Check = new QMenu(menuSettings);
        menuSyntax_Check->setObjectName(QString::fromUtf8("menuSyntax_Check"));
        menuEditor_Language = new QMenu(menuSettings);
        menuEditor_Language->setObjectName(QString::fromUtf8("menuEditor_Language"));
        menuBNM_Event_Convention = new QMenu(menuSettings);
        menuBNM_Event_Convention->setObjectName(QString::fromUtf8("menuBNM_Event_Convention"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QString::fromUtf8("menuTools"));
        BravenewmodderClass->setMenuBar(menuBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuSettings->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNew_Mod);
        menuFile->addAction(actionLoad_Mod);
        menuFile->addAction(actionSave_Mod);
        menuFile->addAction(actionExport_Mod);
        menuFile->addSeparator();
        menuFile->addAction(actionUndo);
        menuFile->addAction(actionExit);
        menuSettings->addAction(menuSyntax_Check->menuAction());
        menuSettings->addAction(actionAdd_New_Syntax);
        menuSettings->addSeparator();
        menuSettings->addAction(menuBNM_Event_Convention->menuAction());
        menuSettings->addAction(actionMod_Settings);
        menuSettings->addSeparator();
        menuSettings->addAction(actionEditor_Settings);
        menuSettings->addAction(menuEditor_Language->menuAction());
        menuSyntax_Check->addAction(actionForce_Check);
        menuSyntax_Check->addAction(actionSuggested);
        menuSyntax_Check->addAction(actionOff);
        menuEditor_Language->addAction(actionEnglish);
        menuBNM_Event_Convention->addAction(actionEnable);
        menuBNM_Event_Convention->addAction(actionDisable);
        menuHelp->addAction(actionHelp);
        menuHelp->addAction(actionAbout);
        menuTools->addAction(actionCreate_QuickScript);
        menuTools->addAction(actionEvent_Renumeration);
        menuTools->addAction(actionGenerate_List);
        menuTools->addAction(actionLocalisation_Check);
        menuTools->addAction(actionImport_Content);

        retranslateUi(BravenewmodderClass);

        tbxMain->setCurrentIndex(0);
        tabWidget->setCurrentIndex(4);
        tabWidget_2->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(BravenewmodderClass);
    } // setupUi

    void retranslateUi(QMainWindow *BravenewmodderClass)
    {
        BravenewmodderClass->setWindowTitle(QApplication::translate("BravenewmodderClass", "Bravenewmodder", 0, QApplication::UnicodeUTF8));
        actionNew_Mod->setText(QApplication::translate("BravenewmodderClass", "New Mod", 0, QApplication::UnicodeUTF8));
        actionLoad_Mod->setText(QApplication::translate("BravenewmodderClass", "Load Mod", 0, QApplication::UnicodeUTF8));
        actionSave_Mod->setText(QApplication::translate("BravenewmodderClass", "Save Mod", 0, QApplication::UnicodeUTF8));
        actionExport_Mod->setText(QApplication::translate("BravenewmodderClass", "Export Mod", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("BravenewmodderClass", "Exit", 0, QApplication::UnicodeUTF8));
        actionForce_Check->setText(QApplication::translate("BravenewmodderClass", "Forced", 0, QApplication::UnicodeUTF8));
        actionSuggested->setText(QApplication::translate("BravenewmodderClass", "Suggested", 0, QApplication::UnicodeUTF8));
        actionOff->setText(QApplication::translate("BravenewmodderClass", "Off", 0, QApplication::UnicodeUTF8));
        actionUnlimited_Play->setText(QApplication::translate("BravenewmodderClass", "Unlimited Play", 0, QApplication::UnicodeUTF8));
        actionHelp->setText(QApplication::translate("BravenewmodderClass", "Help", 0, QApplication::UnicodeUTF8));
        actionAbout->setText(QApplication::translate("BravenewmodderClass", "About", 0, QApplication::UnicodeUTF8));
        actionAdd_New_Syntax->setText(QApplication::translate("BravenewmodderClass", "Add New Syntax...", 0, QApplication::UnicodeUTF8));
        actionManage_My_Mod->setText(QApplication::translate("BravenewmodderClass", "Mod Settings", 0, QApplication::UnicodeUTF8));
        actionEvent_Renumeration->setText(QApplication::translate("BravenewmodderClass", "Event Renumeration", 0, QApplication::UnicodeUTF8));
        actionLocalisation_Check->setText(QApplication::translate("BravenewmodderClass", "Localisation Check", 0, QApplication::UnicodeUTF8));
        actionCreate_QuickScript->setText(QApplication::translate("BravenewmodderClass", "Create QuickScript", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionCreate_QuickScript->setToolTip(QApplication::translate("BravenewmodderClass", "Create a user-defined script to be added to any event", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionGenerate->setText(QApplication::translate("BravenewmodderClass", "Generate...", 0, QApplication::UnicodeUTF8));
        actionGenerate_List->setText(QApplication::translate("BravenewmodderClass", "Generate List", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        actionGenerate_List->setToolTip(QApplication::translate("BravenewmodderClass", "Create a list from two separate lists. Greco-Roman. Greco-Slavic", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        actionImport_Content->setText(QApplication::translate("BravenewmodderClass", "Import EUIII Content", 0, QApplication::UnicodeUTF8));
        actionUndo->setText(QApplication::translate("BravenewmodderClass", "Undo", 0, QApplication::UnicodeUTF8));
        actionEditor_Settings->setText(QApplication::translate("BravenewmodderClass", "Editor Settings", 0, QApplication::UnicodeUTF8));
        actionEnglish->setText(QApplication::translate("BravenewmodderClass", "English", 0, QApplication::UnicodeUTF8));
        actionEnable->setText(QApplication::translate("BravenewmodderClass", "Enable", 0, QApplication::UnicodeUTF8));
        actionDisable->setText(QApplication::translate("BravenewmodderClass", "Disable", 0, QApplication::UnicodeUTF8));
        actionMod_Settings->setText(QApplication::translate("BravenewmodderClass", "Mod Settings", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("BravenewmodderClass", "File Options", 0, QApplication::UnicodeUTF8));
        pushButton_21->setText(QApplication::translate("BravenewmodderClass", "Original Doc.", 0, QApplication::UnicodeUTF8));
        pushButton_22->setText(QApplication::translate("BravenewmodderClass", "Clear Entry", 0, QApplication::UnicodeUTF8));
        pushButton_23->setText(QApplication::translate("BravenewmodderClass", "Syntax Check", 0, QApplication::UnicodeUTF8));
        pushButton_24->setText(QApplication::translate("BravenewmodderClass", "New File", 0, QApplication::UnicodeUTF8));
        pushButton_25->setText(QApplication::translate("BravenewmodderClass", "New Entry", 0, QApplication::UnicodeUTF8));
        pushButton_26->setText(QApplication::translate("BravenewmodderClass", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_27->setText(QApplication::translate("BravenewmodderClass", "Preview", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabCommon), QApplication::translate("BravenewmodderClass", "Common", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("BravenewmodderClass", "File Options", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("BravenewmodderClass", "Original Doc.", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("BravenewmodderClass", "Clear Entry", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("BravenewmodderClass", "Syntax Check", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("BravenewmodderClass", "New File", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("BravenewmodderClass", "New Entry", 0, QApplication::UnicodeUTF8));
        pushButton_11->setText(QApplication::translate("BravenewmodderClass", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("BravenewmodderClass", "Preview", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tab), QApplication::translate("BravenewmodderClass", "Decisions", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("BravenewmodderClass", "File Options", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("BravenewmodderClass", "Original Doc.", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("BravenewmodderClass", "Clear Entry", 0, QApplication::UnicodeUTF8));
        pushButton_16->setText(QApplication::translate("BravenewmodderClass", "Syntax Check", 0, QApplication::UnicodeUTF8));
        pushButton_17->setText(QApplication::translate("BravenewmodderClass", "New File", 0, QApplication::UnicodeUTF8));
        pushButton_18->setText(QApplication::translate("BravenewmodderClass", "New Entry", 0, QApplication::UnicodeUTF8));
        pushButton_19->setText(QApplication::translate("BravenewmodderClass", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_20->setText(QApplication::translate("BravenewmodderClass", "Preview", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(TabEvents), QApplication::translate("BravenewmodderClass", "Events", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("BravenewmodderClass", "Advisors", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("BravenewmodderClass", "Countries", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("BravenewmodderClass", "Diplomacy", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("BravenewmodderClass", "Provinces", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("BravenewmodderClass", "File Options", 0, QApplication::UnicodeUTF8));
        pushButton_35->setText(QApplication::translate("BravenewmodderClass", "Original Doc.", 0, QApplication::UnicodeUTF8));
        pushButton_36->setText(QApplication::translate("BravenewmodderClass", "Clear Entry", 0, QApplication::UnicodeUTF8));
        pushButton_37->setText(QApplication::translate("BravenewmodderClass", "Syntax Check", 0, QApplication::UnicodeUTF8));
        pushButton_38->setText(QApplication::translate("BravenewmodderClass", "New File", 0, QApplication::UnicodeUTF8));
        pushButton_39->setText(QApplication::translate("BravenewmodderClass", "New Entry", 0, QApplication::UnicodeUTF8));
        pushButton_40->setText(QApplication::translate("BravenewmodderClass", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_41->setText(QApplication::translate("BravenewmodderClass", "Preview", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("BravenewmodderClass", "Wars", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabHistory), QApplication::translate("BravenewmodderClass", "History", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabInterface), QApplication::translate("BravenewmodderClass", "Interface", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabLocalisation), QApplication::translate("BravenewmodderClass", "Localisation", 0, QApplication::UnicodeUTF8));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QApplication::translate("BravenewmodderClass", "Text", 0, QApplication::UnicodeUTF8));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_8), QApplication::translate("BravenewmodderClass", "Provinces", 0, QApplication::UnicodeUTF8));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_9), QApplication::translate("BravenewmodderClass", "Rivers", 0, QApplication::UnicodeUTF8));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_10), QApplication::translate("BravenewmodderClass", "Terrain", 0, QApplication::UnicodeUTF8));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_11), QApplication::translate("BravenewmodderClass", "Topology", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabMap), QApplication::translate("BravenewmodderClass", "Map", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("BravenewmodderClass", "File Options", 0, QApplication::UnicodeUTF8));
        pushButton_28->setText(QApplication::translate("BravenewmodderClass", "Original Doc.", 0, QApplication::UnicodeUTF8));
        pushButton_29->setText(QApplication::translate("BravenewmodderClass", "Clear Entry", 0, QApplication::UnicodeUTF8));
        pushButton_30->setText(QApplication::translate("BravenewmodderClass", "Syntax Check", 0, QApplication::UnicodeUTF8));
        pushButton_31->setText(QApplication::translate("BravenewmodderClass", "New File", 0, QApplication::UnicodeUTF8));
        pushButton_32->setText(QApplication::translate("BravenewmodderClass", "New Entry", 0, QApplication::UnicodeUTF8));
        pushButton_33->setText(QApplication::translate("BravenewmodderClass", "Save", 0, QApplication::UnicodeUTF8));
        pushButton_34->setText(QApplication::translate("BravenewmodderClass", "Preview", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabMissions), QApplication::translate("BravenewmodderClass", "Missions", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tab_12), QApplication::translate("BravenewmodderClass", "Save Games", 0, QApplication::UnicodeUTF8));
        tbxMain->setTabText(tbxMain->indexOf(tabReference), QApplication::translate("BravenewmodderClass", "Reference", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("BravenewmodderClass", "File", 0, QApplication::UnicodeUTF8));
        menuSettings->setTitle(QApplication::translate("BravenewmodderClass", "Settings", 0, QApplication::UnicodeUTF8));
        menuSyntax_Check->setTitle(QApplication::translate("BravenewmodderClass", "Syntax Check Mode", 0, QApplication::UnicodeUTF8));
        menuEditor_Language->setTitle(QApplication::translate("BravenewmodderClass", "Editor Language", 0, QApplication::UnicodeUTF8));
        menuBNM_Event_Convention->setTitle(QApplication::translate("BravenewmodderClass", "BNM Event Convention", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("BravenewmodderClass", "Help", 0, QApplication::UnicodeUTF8));
        menuTools->setTitle(QApplication::translate("BravenewmodderClass", "Tools", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class BravenewmodderClass: public Ui_BravenewmodderClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BRAVENEWMODDER_H
